// PULSE — flat ESLint config (ESLint 9+)
// Migrated from legacy .eslintrc during Sprint 1.2 step 6 (CI exposed
// that `npm run lint` had been broken locally since the Vite template
// was bumped to ESLint 9). Keep this minimal and opinionated: we want
// lint to actually run, not drown PRs in noise.

import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import globals from 'globals';

export default tseslint.config(
  // --------------------------------------------------------------------
  // Global ignores — files ESLint should never touch.
  // --------------------------------------------------------------------
  {
    ignores: [
      'dist/',
      'build/',
      'coverage/',
      'playwright-report/',
      'test-results/',
      'blob-report/',
      '.vite/',
      'node_modules/',
      // Generated by TanStack Router — never hand-edited, lint would fail on
      // intentional `any`s. Tracked separately via router build.
      'src/routeTree.gen.ts',
    ],
  },

  // --------------------------------------------------------------------
  // TypeScript + React — app source.
  // --------------------------------------------------------------------
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      // "recommended" (not "strict") — keeps signal-to-noise high on a
      // codebase that mixes generated types and third-party libraries.
      ...tseslint.configs.recommended,
    ],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.es2022,
      },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      // React hooks — catches real bugs (missing deps, conditional hooks).
      ...reactHooks.configs.recommended.rules,

      // Fast-refresh — Vite dev server reliability.
      'react-refresh/only-export-components': [
        'warn',
        { allowConstantExport: true },
      ],

      // Unused vars: allow `_prefix` convention for intentional ignores.
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],

      // `any` is warn, not error — paying down slowly is better than a
      // blanket ban that pressures unsafe casts. Contract-test schemas
      // use `z.unknown()` specifically to avoid any leakage.
      '@typescript-eslint/no-explicit-any': 'warn',
    },
  },

  // --------------------------------------------------------------------
  // Test files — relax a handful of rules.
  // --------------------------------------------------------------------
  {
    files: [
      '**/*.test.{ts,tsx}',
      '**/*.spec.{ts,tsx}',
      'tests/**/*.{ts,tsx}',
      'src/**/__tests__/**/*.{ts,tsx}',
    ],
    languageOptions: {
      globals: {
        ...globals.node,
        ...globals.jest,
      },
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      'react-refresh/only-export-components': 'off',
      // Tests commonly use `let foo = defaultValue; try { foo = ... } catch { foo = ... }`
      // as a readable way to express "probe and set on success/failure". The
      // initial assignment is intentional safety, not dead code.
      'no-useless-assignment': 'off',
    },
  },

  // --------------------------------------------------------------------
  // Config files — node/script environment.
  // --------------------------------------------------------------------
  {
    files: ['*.config.{js,ts}', 'vite.config.ts', 'playwright.config.ts', 'vitest.config.ts'],
    languageOptions: {
      globals: {
        ...globals.node,
      },
    },
  },
);
