import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import path from 'path';

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      '@pulse/shared': path.resolve(__dirname, '../pulse-shared/src/index.ts'),
    },
  },
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./src/test/setup.ts', './tests/setup.ts'],
    css: true,
    include: [
      'src/**/*.{test,spec}.{ts,tsx}',
      'tests/**/*.{test,spec}.{ts,tsx}',
    ],
    exclude: [
      'node_modules',
      'dist',
      'tests/e2e/**',
    ],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html', 'json-summary'],
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        'src/**/*.{test,spec}.{ts,tsx}',
        'src/**/__tests__/**',
        'src/test/**',
        // Generated by TanStack Router — any coverage here would be noise.
        'src/routeTree.gen.ts',
        // Type-only modules — v8 can't measure statements/branches/funcs.
        'src/types/**',
        'src/**/*.d.ts',
      ],
      // Regression-blocking thresholds.
      //
      // Philosophy: the baseline today (2026-04-24) is ~11% stmts / ~58%
      // branches / ~23% funcs after Sprint 1.2 + FDD-DSH-070 landing. These
      // thresholds are set slightly below baseline so they catch coverage
      // REGRESSIONS (new code without tests) while tolerating the current
      // debt. Ratchet them up by 2–5% per sprint as coverage grows.
      //
      // Target by end of R1: 60% stmts / 80% branches / 70% funcs.
      // See testing-playbook.md §8.10 for the ratchet rationale.
      thresholds: {
        statements: 10,
        branches: 55,
        functions: 20,
        lines: 10,
        // Per-file thresholds for code paths that are fully tested today.
        // Failing below these means someone broke a pure-function unit test
        // contract — should be rare.
        'src/lib/dashboard/formatDuration.ts': {
          statements: 95,
          branches: 95,
          functions: 95,
          lines: 95,
        },
        'src/lib/api/metrics.ts': {
          // buildParams unit-tested directly (10 tests); fetch* helpers
          // exercised transitively via hook tests but not all branches
          // — hence the modest line/stmt target. Branches are high because
          // buildParams covers most of the decision logic.
          statements: 35,
          branches: 75,
          functions: 15,
          lines: 35,
        },
      },
    },
  },
});
