"""Application configuration via Pydantic Settings. Fails fast at startup on missing/invalid values."""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import yaml
from pydantic_settings import BaseSettings, SettingsConfigDict

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# connections.yaml loader
# ---------------------------------------------------------------------------

def _connections_paths() -> list[Path]:
    """Build list of candidate paths for connections.yaml."""
    paths = [Path("/app/config/connections.yaml")]  # Docker mount (always checked)
    # Local dev: config.py is at pulse/packages/pulse-data/src/config.py
    # connections.yaml is at pulse/config/connections.yaml (3 levels up from src/)
    try:
        local = Path(__file__).resolve().parents[3] / "config" / "connections.yaml"
        paths.insert(0, local)
    except IndexError:
        pass  # Inside Docker, path is shallow — skip local dev path
    return paths


def _load_connections_yaml() -> dict[str, Any]:
    """Load connections.yaml from known paths. Returns empty dict on failure."""
    for path in _connections_paths():
        if path.is_file():
            try:
                with open(path) as f:
                    data = yaml.safe_load(f) or {}
                logger.info("Loaded connections.yaml from %s", path)
                return data
            except Exception:
                logger.warning("Failed to parse connections.yaml at %s", path, exc_info=True)
    logger.info("No connections.yaml found — using env vars only")
    return {}


def _extract_jenkins_jobs(connections: dict[str, Any]) -> list[dict[str, str]]:
    """Extract Jenkins job configs.

    Primary source: jenkins-job-mapping.json (auto-generated by SCM scan).
    Generates one job entry per prd_job in the mapping, with standard
    deployment/production patterns.

    Fallback: connections.yaml scope.jobs (manual list, backward compat).
    """
    # Primary: load all PRD jobs from jenkins-job-mapping.json
    for path in _connections_paths():
        mapping_path = path.parent / "jenkins-job-mapping.json"
        if mapping_path.is_file():
            try:
                import json
                with open(mapping_path) as f:
                    mapping = json.load(f)
                jobs: list[dict[str, str]] = []
                for repo, data in mapping.items():
                    if repo.startswith("_"):
                        continue
                    for job_name in data.get("prd_jobs", []):
                        jobs.append({
                            "fullName": job_name,
                            "deploymentPattern": ".*",
                            "productionPattern": "(?i)prd|prod|production",
                        })
                if jobs:
                    logger.info(
                        "Loaded %d PRD jobs from jenkins-job-mapping.json",
                        len(jobs),
                    )
                    return jobs
            except Exception:
                logger.warning("Failed to load jenkins-job-mapping.json for jobs", exc_info=True)

    # Fallback: connections.yaml manual list
    for conn in connections.get("connections", []):
        if conn.get("source") == "jenkins":
            return conn.get("scope", {}).get("jobs", [])
    return []


def _build_job_to_repo_map(connections: dict[str, Any]) -> dict[str, str]:
    """Build a reverse map: jenkins_job_fullName -> github_repo_name.

    Uses jenkins-job-mapping.json alongside connections.yaml to resolve
    which GitHub repo each Jenkins job belongs to.
    """
    job_to_repo: dict[str, str] = {}

    # Strategy 1: Load from jenkins-job-mapping.json (generated by mapper script)
    for path in _connections_paths():
        mapping_path = path.parent / "jenkins-job-mapping.json"
        if mapping_path.is_file():
            try:
                import json
                with open(mapping_path) as f:
                    mapping = json.load(f)
                for repo, data in mapping.items():
                    if repo.startswith("_"):
                        continue
                    # Strip org prefix for consistency (e.g., "webmotors-private/repo" -> "repo")
                    repo_short = repo.split("/", 1)[-1] if "/" in repo else repo
                    for job_name in data.get("prd_jobs", []):
                        job_to_repo[job_name] = repo_short
                    for job_name in data.get("all_jobs", []):
                        if job_name not in job_to_repo:
                            job_to_repo[job_name] = repo_short
                logger.info(
                    "Loaded job→repo mapping: %d jobs across %d repos from %s",
                    len(job_to_repo), len(mapping) - 1, mapping_path,
                )
            except Exception:
                logger.warning("Failed to load jenkins-job-mapping.json", exc_info=True)
            break

    return job_to_repo


class Settings(BaseSettings):
    """Environment-driven configuration for pulse-data.

    All values are read from environment variables (case-insensitive).
    The app will refuse to start if required variables are missing.
    """

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
    )

    # PostgreSQL — PULSE main database
    database_url: str = "postgresql+asyncpg://pulse:pulse@localhost:5432/pulse"

    # Kafka
    kafka_brokers: str = "localhost:9092"

    # ---- Source API Connectors ----

    # GitHub
    github_token: str = ""
    github_org: str = "webmotors-private"
    github_api_url: str = "https://api.github.com"

    # Jira Cloud
    jira_base_url: str = ""
    jira_email: str = ""
    jira_api_token: str = ""
    jira_projects: str = ""  # Comma-separated project keys (e.g., "DESC,ENO,ANCR")

    # Jenkins
    jenkins_base_url: str = ""
    jenkins_username: str = ""
    jenkins_api_token: str = ""

    # Redis
    redis_url: str = "redis://localhost:6379"

    # Multi-tenancy — single default tenant in MVP
    default_tenant_id: str = "00000000-0000-0000-0000-000000000001"

    # Dynamic Jira Discovery (ADR-014)
    dynamic_jira_discovery_enabled: bool = False
    internal_api_token: str = ""

    # Application
    app_name: str = "pulse-data"
    app_version: str = "0.1.0"
    debug: bool = False
    log_level: str = "INFO"

    @property
    def async_database_url(self) -> str:
        """Ensure the database URL uses the asyncpg driver."""
        url = self.database_url
        if url.startswith("postgresql://"):
            url = url.replace("postgresql://", "postgresql+asyncpg://", 1)
        return url

    @property
    def kafka_broker_list(self) -> list[str]:
        return [b.strip() for b in self.kafka_brokers.split(",")]

    @property
    def jira_project_list(self) -> list[str]:
        """Parse comma-separated Jira project keys."""
        if not self.jira_projects:
            return []
        return [p.strip() for p in self.jira_projects.split(",") if p.strip()]

    @property
    def jenkins_jobs(self) -> list[dict[str, str]]:
        """Jenkins job configs loaded from connections.yaml."""
        if not hasattr(self, "_jenkins_jobs_cache"):
            conns = _load_connections_yaml()
            object.__setattr__(self, "_jenkins_jobs_cache", _extract_jenkins_jobs(conns))
        return self._jenkins_jobs_cache  # type: ignore[return-value]

    @property
    def jenkins_job_to_repo(self) -> dict[str, str]:
        """Reverse map: Jenkins job fullName -> GitHub repo short name."""
        if not hasattr(self, "_jenkins_job_to_repo_cache"):
            conns = _load_connections_yaml()
            object.__setattr__(self, "_jenkins_job_to_repo_cache", _build_job_to_repo_map(conns))
        return self._jenkins_job_to_repo_cache  # type: ignore[return-value]


# Singleton — imported across the app
settings = Settings()
