/**
 * Route tree for TanStack Router.
 *
 * In production, this would be auto-generated by @tanstack/router-vite-plugin.
 * For the skeleton, routes are manually wired.
 */
import { rootRoute } from './routes/__root';
import { homeRoute } from './routes/_dashboard/home';
import { doraRoute } from './routes/_dashboard/metrics/dora';
import { cycleTimeRoute } from './routes/_dashboard/metrics/cycle-time';
import { throughputRoute } from './routes/_dashboard/metrics/throughput';
import { leanRoute } from './routes/_dashboard/metrics/lean';
import { sprintsRoute } from './routes/_dashboard/metrics/sprints';
import { prsRoute } from './routes/_dashboard/prs';
import { integrationsRoute } from './routes/_dashboard/integrations';
import { pipelineMonitorRoute } from './routes/_dashboard/pipeline-monitor';

export const routeTree = rootRoute.addChildren([
  homeRoute,
  doraRoute,
  cycleTimeRoute,
  throughputRoute,
  leanRoute,
  sprintsRoute,
  prsRoute,
  integrationsRoute,
  pipelineMonitorRoute,
]);
